branch-defaults:
  awsDeployement:
    environment: gamehub-env
  master:
    environment: gamehub-env
    group_suffix: null
environment-defaults:
  gamehub-env:
    branch: null
    repository: null
global:
  application_name: gamehub-backend
  branch: null
  default_ec2_keyname: gamehub_backend
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
